In [1]:
import pandas as pd

In [2]:
traindf = pd.read_csv('data/trainData.csv') # creating a data frame object
                                            # for the csv file

In [3]:
traindf.shape # to see the number of rows and columns respectively

(31527, 11)

In [4]:
traindf.isnull() # shows the null/missing values to be true

,Unnamed: 0,year,month,day,hour,PM2.5,temperature,pressure,rain,wind_direction,wind_speed
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
31522,False,False,False,False,False,False,False,False,False,False,False
31523,False,False,False,False,False,False,False,False,False,False,False
31524,False,False,False,False,False,False,False,False,False,False,False
31525,False,False,False,False,False,False,False,False,False,False,False
31526,False,False,False,False,False,False,False,False,False,False,False

In [5]:
print("\nThe total number of NaN values (missing values) under each column is :-\n")
print(traindf.isnull().sum()) # to print the count of number of missing
                              # values under each column
print("\nEnd_of_File\n\n")

The total number of NaN values (missing values) under each column is :-

Unnamed: 0         0
year              15
month              6
day               20
hour               8
PM2.5             14
temperature       19
pressure          27
rain              12
wind_direction    60
wind_speed        25
dtype: int64

End_of_File